### ISSUE TITLE
Talks and posters 

### ISSUE THREAD

**Issue by hlym** [cuwip-nyc/cuwip-nyc.github.io#11]
Please create a new page linked from the schedule for 'Student Talks and Posters'

On this page include the following information -

Talks
Time: 9:45 am on Sunday January 14th 2018
Format: 10 minute talk + 2 minutes of questions
Computing: Talks will be displayed from a PC computer. PDF format is strongly preferred but power point will also be available. 
We will ask you to upload the talk to a dropbox folder by the evening of January 11th, 2018. Details of how to do this will come later.

Posters
Time: 11:00 - 12:00 pm on Sunday, January 14th 2018.
Format: preferred poster format is A0 vertical (841 x 1189 mm or 33.1 x 46.8 in). This is the largest space available for your poster. 
Set-up: We will provide boards to put the posters up on. The posters should be put up during breakfast on Sunday morning. The posters must be printed beforehand.

**Comment by hedbergj** [comment]
It's here:

[https://cuwip-nyc.github.io/events/#studentTalks](https://cuwip-nyc.github.io/events/#studentTalks)
