### ISSUE TITLE
breakout session description

### ISSUE THREAD

**Issue by hlym** [cuwip-nyc/cuwip-nyc.github.io#13]
Please edit the 'grad school' breakout session - 

It should be titled "Graduate School and Fellowship Applications"

Description: 
Hear from a panel of faculty and graduate students who have served on admissions committees, recently applied to graduate school, and/or won fellowships. The session will open with a brief introduction by each panelists followed by a moderated panel discussion. In the second half, the panel will open for questions about applying to graduate school, being competitive in fellowship applications, and more.

**Comment by hedbergj** [comment]
updated
 
[https://cuwip-nyc.github.io/events/#breakouts](https://cuwip-nyc.github.io/events/#breakouts)
