### ISSUE TITLE
topic table titles, hosts and descriptions

### ISSUE THREAD

**Issue by hlym** [cuwip-nyc/cuwip-nyc.github.io#14]
see below

**Comment by hlym** [comment]
[topics_www (1).docx](https://github.com/cuwip-nyc/cuwip-nyc.github.io/files/1598110/topics_www.1.docx)

**Comment by hedbergj** [comment]
all there now
[https://cuwip-nyc.github.io/events/#topicTables](https://cuwip-nyc.github.io/events/#topicTables)
