### ISSUE TITLE
networking and grad program fair

### ISSUE THREAD

**Issue by hlym** [cuwip-nyc/cuwip-nyc.github.io#18]
D. E. Shaw Research has asked to correct their name on the website to D. E. Shaw Research (note the periods).

**Comment by hlym** [comment]
Add in - 

Companies:
Memorial Sloan Kettering Cancer Center
American Association of Physics Teachers

Grad programs:
University of Massachusetts Amherst (physics)
Southern Connecticut State University (physics)

**Comment by hedbergj** [comment]
got it!
