### ISSUE TITLE
add speaker info

### ISSUE THREAD

**Issue by hedbergj** [cuwip-nyc/cuwip-nyc.github.io#2]

**Comment by hlym** [comment]
For the Graduate School and Fellowship Applications breakout session:

Mary Putman, Professor of Astronomy
Bio:
Mary Putman has been a professor in the Astronomy Department at Columbia since 2008. She was previously on the faculty at the University of Michigan and a Hubble Postdoctoral Fellow at the University of Colorado. Putman has published over 100 refereed publications with over 5,000 citations and is frequently invited to give review talks and write review articles in her field of gaseous galaxy evolution. One of her favorite parts of her job is completing research with the impressive Columbia undergraduate and graduate students.
![unnamed](https://user-images.githubusercontent.com/3005385/33239592-48c6f0d0-d2a5-11e7-90b4-e33dc12a73ab.jpg)

**Comment by hlym** [comment]
Susan Clark is a NASA Hubble Postdoctoral Fellow at the Institute for Advanced Study in Princeton, New Jersey. She studies cosmic magnetism and the interstellar medium-- the stuff between the stars in a galaxy. Susan received her B.S. in Physics from the University of North Carolina at Chapel Hill, and her Ph.D. in Astronomy from Columbia University.
![myface](https://user-images.githubusercontent.com/3005385/33239587-3207fc0e-d2a5-11e7-99fe-fa8419de0092.jpeg)

**Comment by amdastro** [comment]
Stephanie Wortel-Londing will be a panelist in the tangential careers panel, which is one of the breakout sessions. 



Bio:

Stephanie Wortel-London acts as the Director of Education at the New York Academy of Sciences, overseeing the Academy’s Science Alliance and Virtual Mentoring Programs.

Prior to assuming this role, Stephanie served as Program Manager for the Afterschool STEM Mentoring Program in New York City and Newark, NJ for five years. Stephanie graduated magna cum laude in Astronomy-Physics at Colgate University, where she received the 1819 Award. After moving to New York City, she worked in research projects through the Astrophysics Department of the American Museum of Natural History (AMNH) and completed the New York City Teaching Fellowship with an MSEd in Science Education from Lehman College. She is a New York State Certified Earth Science teacher. Prior to joining the Academy, Stephanie taught Earth Science in a South Bronx public school and wrote curricula for Youth Initiatives and the Space Show at AMNH.

Areas of research include quasar optical variability, stellar evolution, astrometry of brown dwarfs, and the development of science identity in groups historically under-represented in STEM through informal learning experiences. She is preparing to defend her PhD dissertation in Science Education Research at Stony Brook University's Institute for STEM Education, and serves as an Adjunct Professor for the Space Systems course in the AMNH Master of Arts in Teaching Residency graduate program. She also serves on the Associate Board of the Red Hook Initiative in Brooklyn.


![wortel-london](https://user-images.githubusercontent.com/11985140/33442496-4c475c42-d5c3-11e7-95e5-747e57033a54.jpeg)

**Comment by amdastro** [comment]
Jehanne Gillo will be on our Saturday panel.

Bio:

Dr. Jehanne Gillo has worked at the Department of Energy since February 2000.  Dr. Gillo first joined the Office of Science’s Office of High Energy and Nuclear Physics, Division of Nuclear Physics at the U.S. Department of Energy as Program Manager for Facilities & Instrumentation.  Dr. Gillo took her present position as the Director of the Facilities and Project Management Division, Office of Nuclear Physics, Department of Energy in October 2005, where she is responsible for the operations of the nuclear physics scientific user facilities, large construction projects, fabrication of scientific instrumentation, accelerator research and development, and the nuclear physics SBIR/STTR program.  Since 2008, she also assumed responsibility as the deputy to the Associate Director of the Office of Nuclear Physics.  In addition, she is Director of the DOE Isotope Program since 2009. She received the Secretary of Energy Excellence Award in October 2012 for her management of the DOE Isotope Program. Dr. Gillo serves on several White House committees and Interagency Groups, including as Chair of the He-3 Interagency Working Group that reports to the White House National Security Staff.  She received the 2016 Achievement Award from the Secretary of the Department of Energy for her efforts as part of the Joint Comprehensive Plan of Action (JCPOA) Support Team. Jehanne Gillo was awarded the 2016 Presidential Rank of Meritorious Executive Award for her accomplishments as the Director of the Nuclear Physics Facilities and Project Management Division.

Dr. Gillo obtained her Bachelor of Science Degree from Juniata College in 1985.  As a graduate student at Texas A&M, Dr. Gillo majored in Nuclear Chemistry with an emphasis in relativistic heavy ion physics research and received her Ph.D. Degree in 1990.  She held the position of Physicist at Los Alamos National Laboratory (LANL) from 1990-2000.  She has worked as a Guest Scientist at the Niels Bohr Institute in Denmark, and has conducted nuclear physics experiments at CERN, RHIC, LANL, and Texas A&M University.


![jehanne gillo](https://user-images.githubusercontent.com/11985140/33442591-81b7166a-d5c3-11e7-9c77-df9dde63927b.jpg)

**Comment by amdastro** [comment]
Rachel Rosen will be on our Saturday panel (did not send photo, I just grabbed one from Google search)


Bio:

Rachel A. Rosen is an assistant professor of theoretical physics at Columbia University.  Her research focuses on gravity and quantum field theory.  In particular, she is interested in using the insights of particles physics to improve our understanding of gravity.  She received her PhD from NYU in 2009 and has held postdoctoral positions at Stockholm University and Columbia University.  She is committed to science communication and has participated in the World Science Festival as a panelist for a salon entitled ``Coming to Grips with Gravity," among other public talks.  In the summer of 2015 and 2017 she co-organized the Sitka Sound Science Workshop for Early Career Theoretical Physicists in Sitka, Alaska. 


![image](https://user-images.githubusercontent.com/11985140/33442661-af72317a-d5c3-11e7-8664-e7f80e35d703.png)

**Comment by hlym** [comment]
For the Graduate School and Fellowship Applications panel - 

Deivid Ribeiro grew up in Cape Cod, Massachusetts, and attended the University of Massachusetts at Dartmouth before transferring to Brown University to complete a B.S. in physics. After graduation, he was accepted into the Bridge to Phd Program at Columbia University, where he worked as a research assistant in Brian Humensky’s laboratory. He is now a 2nd year PhD student in Columbia University Physics department. Deivid has worked on the optical alignment system of a prototype gamma-ray telescope, featuring the novel Schwarzschild-Couder optical design, which is a candidate instrument for the Cherenkov Telescope Array Observatory. Additionally, he is currently working on analysis techniques with VERITAS, the current IACT gamma ray observatory in Arizona.
![deivid ribeiro 1](https://user-images.githubusercontent.com/3005385/33798037-3d3b9212-dd12-11e7-8d83-90ecacd2439c.jpg)

**Comment by amdastro** [comment]
Plenary Speaker: Nadya Mason


Bio:


Professor Nadya Mason received her bachelor's degree in physics from Harvard University in 1995 and received her doctorate in physics in 2001 from Stanford University, working in the group of Aharon Kapitulnik. Her thesis research was on phase transitions in two-dimensional superconductors.

Prior to joining the physics faculty at Illinois, Professor Mason was a Junior Fellow in the Society of Fellows at Harvard University, where she collaborated with Professors Charles Marcus and Michael Tinkham on projects related to both carbon nanotubes and nanostructured superconductors.

Professor Mason's research at Illinois focuses on how electrons behave in low-dimensional, correlated materials, where enhanced interactions are expected to give novel results. The research is relevant to a variety of technologies, including quantum communication, information storage, and qubit control in quantum computers.






![nadyamason](https://user-images.githubusercontent.com/11985140/34131101-43169a58-e418-11e7-8f10-da0780054e44.png)

**Comment by wiscolt923** [comment]
For the Careers Tangential to Physics workshop:

Eliana Ward-Lev is a first year Business Analyst at McKinsey & Company. In this role she helps businesses, non-profits, and government organizations solve complex problems. Eliana graduated from Barnard College in 2017 with degrees in Physics and Computer Science. When she’s not working she volunteers as an EMT for the Central Park Medical Unit and sings in the Barnard-Columbia Chorus.
![profile](https://user-images.githubusercontent.com/21955776/34168875-ac72c530-e4b3-11e7-9c7b-ec40949f4358.jpg)

**Comment by wiscolt923** [comment]
For the Underrepresented in STEM panel:

Mel Abler is a fourth year PhD student at Columbia University focusing on experimental studies of turbulence and nonlinear wave coupling in dipole plasmas, particularly as these studies relate to planetary magnetospheres and ionospheres. They graduated from the University of Wisconsin – Madison in 2014 with degrees in Engineering Physics, Astronomy-Physics, and Applied Mathematics. Both inside and outside the lab, Mel advocates for increased inclusion in physics. They co-founded student chapters of oSTEM (out in Science, Technology, Engineering, and Mathematics) at both Wisconsin and Columbia, recently brought the You Are Welcome Here campaign to Columbia’s Morningside campus, and serves on the local organizing committee for the 2018 CUWiP NYC site. In their “free time” they coach and compete with Row New York, and organization focused on bringing the sport of rowing to everyone regardless of income or ability status.
![mel_headshot-1 1](https://user-images.githubusercontent.com/21955776/34162015-52489624-e4a0-11e7-8ba3-8c2bf5129a89.jpg)

**Comment by wiscolt923** [comment]
For the Underrepresented in STEM workshop:

Kassidy Lundy was born in Queens Village, New York, and graduated from Syracuse University with a B.A. in biophysics in 2016. While at Syracuse, Kassidy worked with Lisa Manning in the Department of Physics to simulate the trajectory of Kupffer’s Vesicle organ in Zebra fish embryos using the principles of the Self-Propelled Particle model. Now, as a Bridge to the PhD scholar at Columbia, Kassidy characterizes CRISPR/Cas9 enzyme kinetics via Atomic Force Microscopy. Following these experiences in computational and experimental biophysics, Kassidy in the process of applying to graduate school programs. Kassidy maintains her desire to volunteer to work with children from members of underrepresented groups, including her own and constantly pushes to encourage holistic and personal growth in professional spaces. 
![lundy 1](https://user-images.githubusercontent.com/21955776/34162584-38d25494-e4a2-11e7-87a0-fcc95cce6b6c.jpg)

**Comment by wiscolt923** [comment]
Another URM STEM:

Moiya McTier is a second year graduate student studying astronomy at Columbia University. She first became interested in astrophysics when she stumbled into an introductory astronomy class as a sophomore at Harvard College. Since then, Moiya has researched several different astronomical phenomena, including galaxy evolution, exoplanets, and Milky Way structure. She splits her time between doing science, talking about it in front of people, and working to make sure marginalized folks can thrive in STEM. 
![headshot](https://user-images.githubusercontent.com/21955776/34167722-876f0bc0-e4b0-11e7-92d4-0e1cd68b50a3.png)

**Comment by wiscolt923** [comment]
![kwame osei-sarfo 1](https://user-images.githubusercontent.com/21955776/34171479-6e0f4012-e4bc-11e7-8734-c33a39e135f1.jpg)
For the URM STEM workshop:

Dr. Kwame Osei-Sarfo currently is the Director the Bridge to Ph.D. Program in the Natural Sciences at Columbia University. As Director, he promotes the participation of underrepresented groups in doctoral programs by providing research, mentoring, and support experiences. Prior to this role, Dr. Osei-Sarfo was a biomedical researcher, who studied multiple subfields in oncology at New York University (NYU) School of Medicine, Weill Cornell Medical College, and Innovimmune Biotherapeutics. Also, Dr. Osei-Sarfo has served an educator to students of various backgrounds at John Jay College for Criminal Justice and New York City College of Technology. Finally, he has volunteered with many organizations that endorse interest in STEM fields for “nontraditional” high school and college students. Dr. Osei-Sarfo understands the need and the importance of improving and fostering support systems to the next wave of underrepresented STEM scholars. 

Dr. Osei-Sarfo received his B.S. in Biology from Xavier University of Louisiana. He earned his Ph.D. in Molecular Oncology and Immunology, by investigating pathways involved in the initiation and development of lymphoma, from NYU Graduate School of Arts and Sciences.

**Comment by wiscolt923** [comment]
For the Undergrad Research workshop:

Dr. Reshmi Mukherjee joined the Barnard faculty in 1997, and is now the Helen Goodhart Altschul Professor of Physics and Astronomy. Her teaching assignments include such courses as "Introductory Physics (Mechanics)," "Experimental Methods in Physics, " "Supervised Individual Research," and "Quantum Physics."

Professor Mukherjee's research interests are in high-energy astrophysics and astroparticle physics. She uses ground-based atmospheric Cherenkov telescopes to study galactic and extragalactic high-energy gamma-ray sources.

One of her current projects is VERITAS (Very Energetic Radiation Imaging Telescope Array System), located in southern Arizona. VERITAS is a major ground-based gamma-ray observatory that enables the study of extragalactic and galactic high energy gamma-ray sources. The VERITAS collaboration uses an array of mirrors at night to detect the quick flashes of blue Cherenkov light that result from gamma-ray air showers.

Professor Mukherjee is also involved with the study of active galaxies, thought to be powered by super-massive black holes at their centers, and unidentified high-energy gamma-ray sources.

![mukherjee_reshmi](https://user-images.githubusercontent.com/21955776/34178340-d983f956-e4d4-11e7-8514-4834670f957b.jpg)

**Comment by hlym** [comment]
On the grad school and fellowship application session -

Brian Cole
I am a full professor of physics at Columbia University and have been on the physics department faculty since 1994.  

My research is in the field of high-energy nuclear physics and is currently focused on experimental studies of ultra-relativistic heavy-ion collisions at the Large Hadron Collider.

![brian cole](https://user-images.githubusercontent.com/3005385/34439548-cad0d776-ec7c-11e7-9f1e-c3e9f19dfa0d.png)

**Comment by hlym** [comment]
On the grad school and fellowship application session -

Elizabeth Culbertson

Elizabeth is a second-year PhD student at Columbia University in the department of Applied Physics and Applied Mathematics and a Presidential Fellow in the School of Engineering and Applied Science. Under Prof. Simon Billinge, she works in applying the pair distribution function (PDF) method to the analysis of x-ray powder diffraction data. In general, the group's focus is on leveraging this technique to do structure determination for aperiodic materials - i.e. nanoparticles, nanocrystalline materials, nanoporous materials, and amorphous materials. In particular, Elizabeth has focused recently on the application of this technique to weakly scattering materials; for example, organic materials and liquids. Elizabeth grew up in Northern Virginia and earned her bachelors degree from Stanford University in 2016, studying engineering physics and computer science. 

![image1 6](https://user-images.githubusercontent.com/3005385/34451398-ed615732-ecf1-11e7-8b54-5e7dbd4b6c82.JPG)

**Comment by hlym** [comment]
For Undergraduate Research - 

Briley Lewis

Undergraduate Student, Columbia Astronomy

Exoplanet detection and characterization, solar system science

Briley Lewis is a senior undergraduate student at Columbia University studying astrophysics. Under Dr. Rebecca Oppenheimer at the American Museum of Natural History, she works on Project 1640, a high-contrast imaging survey to directly image exoplanets and other substellar objects. Additionally, she participated in a summer program with Space Telescope Science Institute in Baltimore, MD; for this project, she works with data from the New Horizons flyby of Pluto to investigate the effects of topography on the movement of ices on Pluto's surface. In addition to research, Briley is involved with Columbia's Undergraduate Astronomy Club, BlueShift, which aims to promote a community between undergraduate students and support their involvement in research and departmental activities. She attended her first CUWiP her sophomore year of undergrad, and is very excited to be helping with this year's conference.
![headshot](https://user-images.githubusercontent.com/3005385/34463438-dca0a91e-ee29-11e7-90a1-f215a754e5d7.jpg)

**Comment by wiscolt923** [comment]
for Careers Tangential to Physics:

![rodanthy tzani](https://user-images.githubusercontent.com/21955776/34593463-05534548-f199-11e7-9f96-8c6a8cbf8c80.jpg)
Rodanthy Tzani is a Vice President and Head of Model Risk in the New York Life Insurance Company. From 2009 to 2017 she was a Supervising Examiner and Risk Analytics Manager in the Model Risk Department of the Supervision Group of the Federal Reserve Bank of New York. During her tenure at the Fed, Rodanthy was a team leader and senior advisor in supervising large domestic and foreign banks in model risk.  She has led numerous examinations evaluating models used for measuring risk and approaches used for calculating risk by large banks. Rodanthy also led the supervision of model risk across the Systemically Important Insurance Companies and established supervising standards of their model risk framework. Before joining the Fed, Rodanthy was the Head of the Structured Finance Risk Management at ACA Capital, where she oversaw the restructuring and winding down of the company during the 2008 crisis. Prior to that she was a Vice President with the Derivatives Group of Moody’s Investors Service. Rodanthy holds a Ph.D. in Theoretical Physics from the City College of CUNY and has spent a number of years in academia conducting research in theoretical physics in various universities in Europe and USA before moving to finance in 2001. She has published a number of papers in refereed journals in both physics and finance. Rodanthy is a native of Greece and lives with her husband, Alexios, and son, Jason, in New York City.

**Comment by wiscolt923** [comment]
[Greg Kaldor Sept 17.pdf](https://github.com/cuwip-nyc/cuwip-nyc.github.io/files/1605373/Greg.Kaldor.Sept.17.pdf)
 for the Careers Tangential to Physics workshop:

**Comment by amdastro** [comment]
Updated bio for plenary speaker Dr. Nadya Mason:


NADYA MASON is a professor of Physics at the University of Illinois at Urbana-Champaign  and Director of the Illinois Materials Research Science and Engineering Center. She earned her PhD in physics from Stanford University and engaged in postdoctoral research as a Junior Fellow at Harvard University. A condensed matter experimentalist, Dr. Mason focuses on electron behavior in low-dimensional materials such as nanowires, graphene, and nano-structured superconductors. Her research is relevant to the fundamental physics of small systems, as well as to applications involving nano-scale and quantum electronic elements. In addition to maintaining a rigorous research program and teaching, Dr. Mason works to increase diversity in the physical sciences, embracing opportunities to encourage and mentor aspiring scientists from underrepresented groups and to promote a welcoming climate within the field. Dr. Mason was named a 2008 Emerging Scholar by Diverse Issues in Higher Education magazine, and was a recipient of the 2009 Denise Denton Emerging Leader Award and the 2012 Maria Goeppert Mayer Award of the American Physical Society (APS). She is a General Councillor of the APS, the former Chair of the APS Committee on Minorities, and serves on the Editorial Board of Physical Review B.

**Comment by wiscolt923** [comment]
Careers Tangential to Physics:

Sarah Campbell is a Data Scientist at Amazon working on Alexa, Amazon’s voice operated personal assistant.  In her current role, she uses machine learning algorithms to create statistical models for natural language understanding, what is considered an AI ‘hard’ problem.  Prior to working at Amazon, Sarah was a post-doctoral researcher at Columbia University working with Bill Zajc and Brain Cole on relativistic heavy ion research, specifically sPHENIX a new detector planned for the Relativistic Heavy Ion Collider at Brookhaven National Laboratory.   In 2002, Sarah graduated with a BA in physics and mathematics from Grinnell College in Grinnell, IA and in 2011 she graduated with a PhD in physics from Stony Brook University in Stony Brook, NY.  Sarah currently lives in the Boston area with her husband, two kids and a dog.
![sarahcampbell](https://user-images.githubusercontent.com/21955776/34686768-ab93c368-f47a-11e7-88da-7ab5ca6c388f.jpg)
