### ISSUE TITLE
resources

### ISSUE THREAD

**Issue by hlym** [cuwip-nyc/cuwip-nyc.github.io#20]
Graduate School and Fellowship Applications handout
[Graduate School and Fellowship Applications - student handout.pdf](https://github.com/cuwip-nyc/cuwip-nyc.github.io/files/1610276/Graduate.School.and.Fellowship.Applications.-.student.handout.pdf)

**Comment by hedbergj** [comment]
great  - I'll leave this open in case there is more to add there.

**Comment by hlym** [comment]
Networking and Graduate School Fair handout
[CUWiP Networking and Graduate School Fair - student handout.pdf](https://github.com/cuwip-nyc/cuwip-nyc.github.io/files/1623317/CUWiP.Networking.and.Graduate.School.Fair.-.student.handout.pdf)
