### ISSUE TITLE
Sunday morning schedule update

### ISSUE THREAD

**Issue by hlym** [cuwip-nyc/cuwip-nyc.github.io#3]
At the LOC meeting Friday (11/10), I believe we changed the Sunday schedule to: Parallel student talks > Plenary 2 > Poster fair

**Comment by hedbergj** [comment]
ok, yes, I see the minutes indicate:

"Sunday:   Parallel   student   talks,   plenary   2,   then   poster   fair"

but then the spreadsheet from J.D. says:

Sunday,   January 14, 2018 |   |  
-- | -- | --
8:30 -   9:00 AM | Breakfast | Columbia
9:00 -   9:45 AM | Plenary II | Columbia
9:45 -   11:00 AM | Parallel Student Talks | Columbia
11:00 -   12:00 PM | Poster Fair + Coffee | Columbia

not sure which to follow?
