### ISSUE TITLE
Add LOC member list somewhere on website

### ISSUE THREAD

**Issue by jrdodd** [cuwip-nyc/cuwip-nyc.github.io#4]
Following a good suggestion from Andrea: we should put the LOC list on the website somewhere - where might be best?

The names: 
Jeremy Dodd (Columbia, Physics)
Laura Havener (Columbia, Physics)
Heather McCarrick (Columbia, Physics)
Kathryn Sutton (Columbia, Physics)
Laura Kay (Barnard)
Myriam Sarachik (CCNY)
James Hedberg (CCNY)
Abigail Murphy (CCNY)
Xiuhong Cai (CCNY)
Kathryn Johnston (Columbia, Astronomy)
David Helfand (Columbia, Astronomy)
Rose Gibson	(Columbia, Astronomy)
Andrea Derdzinski (Columbia, Astronomy)
Summer Ash	(Columbia, Astronomy)
Kursti DeLello (Columbia, Physics)
Huda Qureshi (Columbia, Applied Physics)
Kassidy Lundy (Columbia, Biology / Biophysics)
Mel Abler (Columbia, Applied Physics)

This list is obviously lengthy - not sure of the best way to display it so as not to be too annoying - ideas?

Thanks.

**Comment by hedbergj** [comment]
added to contact page - if there's a better place, let me know. If people want links with their names, let me know those too!
