### ISSUE TITLE
Confirmed participants for the Networking and Graduate School Fair

### ISSUE THREAD

**Issue by hlym** [cuwip-nyc/cuwip-nyc.github.io#5]
Maybe we can make a sub-page about this and link to it from the schedule?

Confirmed participants w/ reps:
Drexel University (physics)
Rutgers (physics)
Yale (astro)
Harvard (astro)
Boston University (physics)
Princeton (astro)
Columbia (astro)
Columbia (physics)

**Comment by hedbergj** [comment]
yes - done!
