### ISSUE TITLE
directions/ transportation

### ISSUE THREAD

**Issue by hlym** [cuwip-nyc/cuwip-nyc.github.io#7]
I think we should add more specific directions, subway stops and lines to get to each hotel and the campuses (esp. from Penn Station and GCT).

**Comment by hedbergj** [comment]
agreed - I'll work on a document for this.

**Comment by hlym** [comment]
Also add in the three maps we put in the program? I know the travel page is getting crowded... or we could do a separate page - 'maps' 

https://github.com/cuwip-nyc/media-assets/blob/master/maps/CUWiP-conference-map.pdf

[CUWiPMaps_ColumbiaBarnard (5).pdf](https://github.com/cuwip-nyc/cuwip-nyc.github.io/files/1603663/CUWiPMaps_ColumbiaBarnard.5.pdf)

![ccny_map](https://user-images.githubusercontent.com/3005385/34569245-3136348a-f136-11e7-9860-c78f4332c20c.png)

**Comment by hedbergj** [comment]
Linked to from travel, but reside in Resources:

https://cuwip-nyc.github.io/resources/#maps
