### ISSUE TITLE
grad and networking fair - more companies to add

### ISSUE THREAD

**Issue by hlym** [cuwip-nyc/cuwip-nyc.github.io#9]
Additions below, thanks!

Companies/ institutions: 
Bank of America
Life-Sci NYC (https://www.lifesci.nyc/students)
OC&C Strategy Consultants
Google

Graduate programs:
NYU Tandon School of Engineering
CUNY Graduate Center

**Comment by hlym** [comment]
Also, could you please link from the fair on the 'schedule' page to the one on the 'events page'? Thanks!

**Comment by hlym** [comment]
One more thing - this event now ends at 10:45am .Thanks.

**Comment by hedbergj** [comment]
all done!
